// <auto-generated />
namespace AirNavigationRaceLive.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class ChannelFunctionality : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ChannelFunctionality));
        
        string IMigrationMetadata.Id
        {
            get { return "201901190106199_ChannelFunctionality"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
